import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

export default function Home() {

  const [job, setJob] = useState('')

  const handleSubmit = () => {

  }

  return (
    <>
      <Head>
        <title>Linkedin Scrapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={(e) => {
          e.preventDefault()
          handleSubmit()
        }} method="POST">
          <div class="shadow sm:overflow-hidden sm:rounded-md">
            <div class="space-y-6 px-4 py-5 sm:p-6 dark:border-gray-700 dark:text-gray-400  dark:bg-gray-800">
              <div class="grid">
                <div class="w-full flex align-bottom gap-1 justify-end" style={{ alignItems: 'flex-end' }}>
                  <div class='w-full flex flex-col'>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Search Job</label>
                    <input type="text" value={job} onChange={(e) => setJob(e.target.value)} id="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 w-96" placeholder="Search Job" required />
                  </div>
                  <div style={{ height: 'fit-content' }}>
                    <button type="submit" class="mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
        <form onSubmit={(e) => {
          e.preventDefault()
          handleSubmit()
        }} method="POST">
          <div class="shadow sm:overflow-hidden sm:rounded-md">
            <div class="space-y-6 px-4 py-5 sm:p-6 dark:border-gray-700 dark:text-gray-400  dark:bg-gray-800">
              <div class="grid">
                <div class="w-full flex align-bottom gap-1 justify-end" style={{ alignItems: 'flex-end' }}>
                  <div class='w-full flex flex-col'>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Search Users</label>
                    <input type="text" value={job} onChange={(e) => setJob(e.target.value)} id="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 w-96" placeholder="Search Users" required />
                  </div>
                  <div style={{ height: 'fit-content' }}>
                    <button type="submit" class="mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
        <form onSubmit={(e) => {
          e.preventDefault()
          handleSubmit()
        }} method="POST">
          <div class="shadow sm:overflow-hidden sm:rounded-md">
            <div class="space-y-6 px-4 py-5 sm:p-6 dark:border-gray-700 dark:text-gray-400  dark:bg-gray-800">
              <div class="grid">
                <div class="w-full flex align-bottom gap-1 justify-end" style={{ alignItems: 'flex-end' }}>
                  <div class='w-full flex flex-col'>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Search Companies</label>
                    <input type="text" value={job} onChange={(e) => setJob(e.target.value)} id="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 w-96" placeholder="Search Companies" required />
                  </div>
                  <div style={{ height: 'fit-content' }}>
                    <button type="submit" class="mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
        <div style={{width: '32.5rem'}} class="shadow sm:overflow-hidden sm:rounded-md mt-5">
          <div class="space-y-6 px-4 py-5 sm:p-6 dark:border-gray-700 dark:text-gray-400  dark:bg-gray-800">
            <div class="grid">
              <div class="w-full flex flex-col">
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Results</label>
                <div>
                  Results Goes Here
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
